# Lecture 5 — Tables

## Tables intro

0-5 mins

In [1]:
import numpy as np
np.set_printoptions(threshold=50)

## Tables

5-15 mins

In [2]:
from datascience import *

In [3]:
Table()

Explain syntax here.

In [4]:
Table().with_columns('Petals', make_array(8, 34, 5))

Petals
8
34
5

In [5]:
Table().with_columns(
    'Petals', make_array(8, 34, 5),
    'Name', make_array('lotus', 'sunflower', 'rose')
)

Petals | Name
8      | lotus
34     | sunflower
5      | rose

No mutation:

In [6]:
flowers = Table().with_columns(
    'Petals', make_array(8, 34, 5),
    'Name', make_array('lotus', 'sunflower', 'rose')
)

flowers.with_column(
    'Color', make_array('pink', 'yellow', 'red')
)

Petals | Name      | Color
8      | lotus     | pink
34     | sunflower | yellow
5      | rose      | red

In [7]:
flowers

Petals | Name
8      | lotus
34     | sunflower
5      | rose

## Mutation

15-25 mins

In [8]:
x = 3

In [9]:
x + 2

5

In [10]:
x

3

Explain mutation for a bit.

In [11]:
x = x + 2
x

5

In [12]:
x + 2

7

In [13]:
flowers

Petals | Name
8      | lotus
34     | sunflower
5      | rose

In [14]:
flowers = flowers.with_column(
    'Color', make_array('pink', 'yellow', 'red')
)
flowers

Petals | Name      | Color
8      | lotus     | pink
34     | sunflower | yellow
5      | rose      | red

## Minard's Map

25-45 mins

In [15]:
minard = Table.read_table('http://inferentialthinking.com/notebooks/minard.csv') # or http://inferentialthinking.com/notebooks/minard.csv
minard

Longitude | Latitude | City        | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

In [16]:
minard.num_columns

5

In [17]:
minard.num_rows

8

In [18]:
minard.labels

('Longitude', 'Latitude', 'City', 'Direction', 'Survivors')

In [19]:
minard.relabeled('City', 'City Name')

Longitude | Latitude | City Name   | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

Run this twice and explain why it breaks the second time.

In [20]:
minard = minard.relabeled('City', 'City Name')
minard

Longitude | Latitude | City Name   | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

In [21]:
minard.column('Survivors')

array([145000, 140000, 127100, 100000,  55000,  24000,  20000,  12000])

In [22]:
minard.column(4)

array([145000, 140000, 127100, 100000,  55000,  24000,  20000,  12000])

In [23]:
minard.column(4).item(0)

145000

Let's add a column:

In [24]:
initial = minard.column('Survivors').item(0)
minard = minard.with_column(
    'Percent Surviving', minard.column('Survivors')/initial
)
minard

Longitude | Latitude | City Name   | Direction | Survivors | Percent Surviving
32        | 54.8     | Smolensk    | Advance   | 145000    | 1
33.2      | 54.9     | Dorogobouge | Advance   | 140000    | 0.965517
34.4      | 55.5     | Chjat       | Advance   | 127100    | 0.876552
37.6      | 55.8     | Moscou      | Advance   | 100000    | 0.689655
34.3      | 55.2     | Wixma       | Retreat   | 55000     | 0.37931
32        | 54.6     | Smolensk    | Retreat   | 24000     | 0.165517
30.4      | 54.4     | Orscha      | Retreat   | 20000     | 0.137931
26.8      | 54.3     | Moiodexno   | Retreat   | 12000     | 0.0827586

(If asked)

In [25]:
minard.set_format('Percent Surviving', PercentFormatter)

Longitude | Latitude | City Name   | Direction | Survivors | Percent Surviving
32        | 54.8     | Smolensk    | Advance   | 145000    | 100.00%
33.2      | 54.9     | Dorogobouge | Advance   | 140000    | 96.55%
34.4      | 55.5     | Chjat       | Advance   | 127100    | 87.66%
37.6      | 55.8     | Moscou      | Advance   | 100000    | 68.97%
34.3      | 55.2     | Wixma       | Retreat   | 55000     | 37.93%
32        | 54.6     | Smolensk    | Retreat   | 24000     | 16.55%
30.4      | 54.4     | Orscha      | Retreat   | 20000     | 13.79%
26.8      | 54.3     | Moiodexno   | Retreat   | 12000     | 8.28%

In [39]:
minard.select('Longitude', 'Direction')

Longitude | Direction
32        | Advance
33.2      | Advance
34.4      | Advance
37.6      | Advance
34.3      | Retreat
32        | Retreat
30.4      | Retreat
26.8      | Retreat

Discussion question: Why does this error?

In [ ]:
minard.select(0, 3).select(3)

In [42]:
minard.select(0, 3).select(1)

Direction
Advance
Advance
Advance
Advance
Retreat
Retreat
Retreat
Retreat

Discussion question: Why does the first one error but the second one not?

In [45]:
minard.select('Survivors') + 1

TypeError: unsupported operand type(s) for +: 'Table' and 'int'

In [46]:
minard.column('Survivors') + 1

array([145001, 140001, 127101, 100001,  55001,  24001,  20001,  12001])

In [ ]:
# sum(minard.select('Survivors')) vs sum(minard.column('Survivors'))

In [30]:
minard.drop('Longitude', 'Latitude', 'Direction')

City Name   | Survivors | Percent Surviving
Smolensk    | 145000    | 100.00%
Dorogobouge | 140000    | 96.55%
Chjat       | 127100    | 87.66%
Moscou      | 100000    | 68.97%
Wixma       | 55000     | 37.93%
Smolensk    | 24000     | 16.55%
Orscha      | 20000     | 13.79%
Moiodexno   | 12000     | 8.28%

In [31]:
minard

Longitude | Latitude | City Name   | Direction | Survivors | Percent Surviving
32        | 54.8     | Smolensk    | Advance   | 145000    | 100.00%
33.2      | 54.9     | Dorogobouge | Advance   | 140000    | 96.55%
34.4      | 55.5     | Chjat       | Advance   | 127100    | 87.66%
37.6      | 55.8     | Moscou      | Advance   | 100000    | 68.97%
34.3      | 55.2     | Wixma       | Retreat   | 55000     | 37.93%
32        | 54.6     | Smolensk    | Retreat   | 24000     | 16.55%
30.4      | 54.4     | Orscha      | Retreat   | 20000     | 13.79%
26.8      | 54.3     | Moiodexno   | Retreat   | 12000     | 8.28%